/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as EcosistemaInnovazioneRouteImport } from './routes/ecosistema-innovazione'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ComeLavoriamoRouteImport } from './routes/come-lavoriamo'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as BandiOpportunitaRouteImport } from './routes/bandi-opportunita'
import { Route as IndexRouteImport } from './routes/index'

const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemaInnovazioneRoute = EcosistemaInnovazioneRouteImport.update({
  id: '/ecosistema-innovazione',
  path: '/ecosistema-innovazione',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeLavoriamoRoute = ComeLavoriamoRouteImport.update({
  id: '/come-lavoriamo',
  path: '/come-lavoriamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const BandiOpportunitaRoute = BandiOpportunitaRouteImport.update({
  id: '/bandi-opportunita',
  path: '/bandi-opportunita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bandi-opportunita': typeof BandiOpportunitaRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-lavoriamo': typeof ComeLavoriamoRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema-innovazione': typeof EcosistemaInnovazioneRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bandi-opportunita': typeof BandiOpportunitaRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-lavoriamo': typeof ComeLavoriamoRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema-innovazione': typeof EcosistemaInnovazioneRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bandi-opportunita': typeof BandiOpportunitaRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/come-lavoriamo': typeof ComeLavoriamoRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema-innovazione': typeof EcosistemaInnovazioneRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bandi-opportunita'
    | '/chi-siamo'
    | '/come-lavoriamo'
    | '/contatti'
    | '/ecosistema-innovazione'
    | '/servizi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bandi-opportunita'
    | '/chi-siamo'
    | '/come-lavoriamo'
    | '/contatti'
    | '/ecosistema-innovazione'
    | '/servizi'
  id:
    | '__root__'
    | '/'
    | '/bandi-opportunita'
    | '/chi-siamo'
    | '/come-lavoriamo'
    | '/contatti'
    | '/ecosistema-innovazione'
    | '/servizi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandiOpportunitaRoute: typeof BandiOpportunitaRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ComeLavoriamoRoute: typeof ComeLavoriamoRoute
  ContattiRoute: typeof ContattiRoute
  EcosistemaInnovazioneRoute: typeof EcosistemaInnovazioneRoute
  ServiziRoute: typeof ServiziRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistema-innovazione': {
      id: '/ecosistema-innovazione'
      path: '/ecosistema-innovazione'
      fullPath: '/ecosistema-innovazione'
      preLoaderRoute: typeof EcosistemaInnovazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-lavoriamo': {
      id: '/come-lavoriamo'
      path: '/come-lavoriamo'
      fullPath: '/come-lavoriamo'
      preLoaderRoute: typeof ComeLavoriamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandi-opportunita': {
      id: '/bandi-opportunita'
      path: '/bandi-opportunita'
      fullPath: '/bandi-opportunita'
      preLoaderRoute: typeof BandiOpportunitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandiOpportunitaRoute: BandiOpportunitaRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ComeLavoriamoRoute: ComeLavoriamoRoute,
  ContattiRoute: ContattiRoute,
  EcosistemaInnovazioneRoute: EcosistemaInnovazioneRoute,
  ServiziRoute: ServiziRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
